version: "2.1"
services:
  mariadb:
    image: mariadb:10.1.38
    environment:
      - MYSQL_ROOT_PASSWORD=ipex
      - MYSQL_DATABASE=ipex
      - MYSQL_USER=ipex
      - MYSQL_PASSWORD=ipex
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysql", "-u", "ipex", "-pipex", "-e", "SELECT 1;"]
      interval: 30s
      timeout: 30s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      mariadb:
        condition: service_healthy

  adminer:
    image: adminer:4.7.1
    ports:
      - 8081:8080
    depends_on:
      mariadb:
        condition: service_healthy